# Parameter Fisik Quadrotor
# Nilai ini diekstrak dari nominal MATLAB Phase 0
# Anda bisa membuat file berbeda (misal: quadrotor_berat.yaml) untuk skenario "Heterogeneous Swarm"
physics:
  mass: 1.0        # kg
  g: 9.81          # m/s^2
  ix: 8.1e-3       # kg.m^2
  iy: 8.1e-3       # kg.m^2
  iz: 14.2e-3      # kg.m^2
  arm_length: 0.24 # meter

actuator_limits:
  thrust_min: -9.81   # N (perturbasi minimum, setara thrust 0 N)
  thrust_max: 10.19   # N (berdasarkan TWR 2:1, max 20 N)
  tau_rp_max: 1.0     # Nm (Batas Torsi Roll/Pitch)
  tau_y_max: 0.2      # Nm (Batas Torsi Yaw)
  angle_max: 0.436    # rad (Batas kemiringan Roll/Pitch, 25 derajat)

actuator_physics:
  kf: 8.54858e-06     # N / (rad/s)^2 (Thrust coefficient)
  km: 1.3677e-07      # Nm / (rad/s)^2 (Torque coefficient)
  tau_m: 0.02         # s (Motor time constant / First-Order Lag)
  omega_max: 1100.0   # rad/s (Batas maksimal putaran baling-baling)
  omega_min: 0.0      # rad/s
